# Generated by Django 4.1 on 2022-08-08 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('feeling', models.CharField(choices=[('R', 'Regret'), ('A', 'Ambivalence'), ('S', 'Satisfied')], default='R', max_length=1)),
                ('poptart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.poptart')),
            ],
        ),
    ]
