# Generated by Django 4.1 on 2022-08-08 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_emotion_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emotion',
            options={'ordering': ['-date']},
        ),
    ]
